name: Docker Image CI

on:
  push:
    branches: [ version-2 ]
  pull_request:
    branches: [ version-2 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/dice-cloud:latest --tag ${{ secrets.DOCKER_HUB_USERNAME }}/dice-cloud:${{ github.run_number }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dice-cloud --all-tags
